# Generated by Django 3.2.25 on 2024-03-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price_difference', '-created')},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='difference',
            new_name='price_difference',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='last_update',
            new_name='updated',
        ),
    ]
